class_name MicroStoryCatalog
extends RefCounted
## Environmental micro-stories — places that ask “what happened here?”
## Off the mini-map. Some hold rewards; many are pure curiosity.


static func grassland_stories() -> Array[Dictionary]:
	## pos = world XZ anchor. kind drives dressing. reason = design intent (not shown to player).
	return [
		{
			"id": &"ash_camp",
			"name": "Cold Ash Camp",
			"pos": Vector3(240, 0, 320),
			"kind": &"camp",
			"bits": 8,
			"msg": "The fire is long dead. Someone counted hex shards in the dirt and left in a hurry.",
			"reward": &"chest_normal",
			"reason": "Abandoned overnight camp near Park SE trail",
		},
		{
			"id": &"wagon_rut",
			"name": "Broken Wagon",
			"pos": Vector3(780, 0, 120),
			"kind": &"wreck",
			"bits": 7,
			"msg": "Axle snapped on the Mile road. Goods are gone — or never were.",
			"reward": &"bits",
			"reason": "Roadside failure implies trade traffic",
		},
		{
			"id": &"cave_bones",
			"name": "Cave Mouth Remains",
			"pos": Vector3(300, 0, 1160),
			"kind": &"bones",
			"bits": 12,
			"msg": "Something large dragged a meal to the cave lip. The hex-stain still glows faintly.",
			"reward": &"chest_rare",
			"reason": "Predator story near hillside cave",
		},
		{
			"id": &"lost_pack",
			"name": "Abandoned Pack",
			"pos": Vector3(-90, 0, -380),
			"kind": &"pack",
			"bits": 6,
			"msg": "A Field Unit pack, zipper torn. The logbook ends mid-sentence.",
			"reward": &"lore",
			"reason": "Explorer vanished north of Park",
		},
		{
			"id": &"digital_plinth",
			"name": "Ruined Hex Plinth",
			"pos": Vector3(520, 0, -900),
			"kind": &"monument",
			"bits": 14,
			"msg": "A cracked monument hums when you step near. The glyphs predate the towns.",
			"reward": &"chest_rare",
			"reason": "Ancient digital culture remnant",
		},
		{
			"id": &"crystal_nest",
			"name": "Crystal Outcrop",
			"pos": Vector3(-340, 0, 480),
			"kind": &"crystal",
			"bits": 10,
			"msg": "Blue crystals push through grass like frozen lightning.",
			"reward": &"material",
			"reason": "Resource curiosity west of Park",
		},
		{
			"id": &"stone_ring_east",
			"name": "East Stone Ring",
			"pos": Vector3(1500, 0, 220),
			"kind": &"stones",
			"bits": 9,
			"msg": "Seven stones lean toward the sunrise. Offerings of flowers remain fresh.",
			"reward": &"none",
			"reason": "Ritual landmark toward Market Mile",
		},
		{
			"id": &"bridge_ruin",
			"name": "Collapsed Footbridge",
			"pos": Vector3(680, 0, -560),
			"kind": &"bridge",
			"bits": 8,
			"msg": "Planks hang over a dry cut. The stream moved — or someone diverted it.",
			"reward": &"none",
			"reason": "Hydrology change story near Mere corridor",
		},
		{
			"id": &"cabin_shell",
			"name": "Cabin Shell",
			"pos": Vector3(-620, 0, 820),
			"kind": &"cabin",
			"bits": 11,
			"msg": "Four walls, no roof. A kettle still sits on the cold stove.",
			"reward": &"chest_normal",
			"reason": "Failed homestead toward Grove",
		},
		{
			"id": &"giant_log",
			"name": "Nurse Log",
			"pos": Vector3(160, 0, 860),
			"kind": &"meglog",
			"bits": 7,
			"msg": "A fallen giant hosts moss, mushrooms, and a hollow wide enough to crawl.",
			"reward": &"none",
			"reason": "Forest ecology vignette near Pine Hollow",
		},
		{
			"id": &"hidden_pond",
			"name": "Reed Pond",
			"pos": Vector3(980, 0, 700),
			"kind": &"pond",
			"bits": 8,
			"msg": "Dragonflies stitch the surface. Footprints circle the bank — two toes, not boots.",
			"reward": &"none",
			"reason": "Wildlife watering hole",
		},
		{
			"id": &"trickle_fall",
			"name": "Trickle Falls",
			"pos": Vector3(420, 0, 1480),
			"kind": &"waterfall",
			"bits": 9,
			"msg": "A thin ribbon of water over rock. Cooler air pools in the bowl below.",
			"reward": &"none",
			"reason": "Sensory landmark toward Salty",
		},
		{
			"id": &"watch_stump",
			"name": "Watchtower Stump",
			"pos": Vector3(80, 0, -1680),
			"kind": &"tower",
			"bits": 10,
			"msg": "Only the base remains. From here the drive-in screen is a pale coin on the horizon.",
			"reward": &"lore",
			"reason": "Old ranger post toward Reels",
		},
		{
			"id": &"shrine_petal",
			"name": "Petal Shrine",
			"pos": Vector3(1900, 0, 900),
			"kind": &"shrine",
			"bits": 13,
			"msg": "A low altar of stacked rock. Fresh petals — someone still visits.",
			"reward": &"chest_normal",
			"reason": "Living folk practice SE of Mile",
		},
		{
			"id": &"meteor_scar",
			"name": "Scorch Scar",
			"pos": Vector3(2100, 0, 2100),
			"kind": &"meteor",
			"bits": 16,
			"msg": "Grass won't grow in the black ring. A warm shard ticks like a clock.",
			"reward": &"chest_rare",
			"reason": "Recent digital meteor event seed",
		},
		{
			"id": &"statue_half",
			"name": "Half Statue",
			"pos": Vector3(-1100, 0, 200),
			"kind": &"statue",
			"bits": 10,
			"msg": "A stone figure broken at the waist. The raised hand still points west.",
			"reward": &"lore",
			"reason": "Navigation lore toward Storm Prairie",
		},
		{
			"id": &"bird_scaffold",
			"name": "Nest Scaffold",
			"pos": Vector3(-180, 0, -220),
			"kind": &"nest",
			"bits": 6,
			"msg": "Twigs woven into a dead pine. Eggshells glitter with hex dust.",
			"reward": &"none",
			"reason": "Flying fauna habitat cue",
		},
		{
			"id": &"traveler_bedroll",
			"name": "Traveler Bedroll",
			"pos": Vector3(1100, 0, -200),
			"kind": &"camp",
			"bits": 7,
			"msg": "Bedroll still warm to the touch. The traveler can't be far.",
			"reward": &"none",
			"reason": "Hooks runtime traveler encounter",
		},
		{
			"id": &"flood_marker",
			"name": "Flood Marker",
			"pos": Vector3(640, 0, -380),
			"kind": &"marker",
			"bits": 5,
			"msg": "A painted stake reads HIGH WATER — years ago. The mud line is higher.",
			"reward": &"none",
			"reason": "Stream corridor memory",
		},
		{
			"id": &"hex_garden",
			"name": "Wild Hex Garden",
			"pos": Vector3(40, 0, 560),
			"kind": &"garden",
			"bits": 9,
			"msg": "Someone planted glowing herbs in a circle. Weeds are winning.",
			"reward": &"material",
			"reason": "Failed cultivation story",
		},
		{
			"id": &"cliff_cairn",
			"name": "Cliff Cairn",
			"pos": Vector3(2680, 0, 3180),
			"kind": &"stones",
			"bits": 8,
			"msg": "Stacked stones mark a climb. Wind sings through the gaps.",
			"reward": &"none",
			"reason": "Guidance toward Fields / Bluffs",
		},
		{
			"id": &"grove_picnic",
			"name": "Forgotten Picnic",
			"pos": Vector3(-1480, 0, 1300),
			"kind": &"picnic",
			"bits": 6,
			"msg": "A blanket, two cups, and a note: BACK SOON. The ink has faded.",
			"reward": &"lore",
			"reason": "Human absence near Grove",
		},
		{
			"id": &"reels_projector",
			"name": "Dumped Projector",
			"pos": Vector3(140, 0, -3100),
			"kind": &"wreck",
			"bits": 11,
			"msg": "A cinema projector half-buried in sand. The last reel is labeled DON'T PLAY.",
			"reward": &"chest_normal",
			"reason": "Risky Reels culture spill",
		},
		{
			"id": &"fields_scare",
			"name": "Scare Hex",
			"pos": Vector3(3200, 0, 3400),
			"kind": &"scarecrow",
			"bits": 7,
			"msg": "A scarecrow with a hex-lamp head. It still turns toward footsteps.",
			"reward": &"none",
			"reason": "Farm folklore at Fatal Fields",
		},
	]


static func grassland_viewpoints() -> Array[Dictionary]:
	return [
		{"id": &"hill_whisper", "name": "Whisper Hill", "pos": Vector3(200, 0, 100), "msg": "Park roofs tile the green bowl. Wind carries market bells."},
		{"id": &"mere_glint", "name": "Mere Glint", "pos": Vector3(1180, 0, -1180), "msg": "Water flashes between pines — the lake is close."},
		{"id": &"bluff_wind", "name": "Bluff Wind Seat", "pos": Vector3(3300, 0, 4000), "msg": "The grassland ends in stone. Clouds race the ridge."},
		{"id": &"grove_canopy", "name": "Grove Canopy Gap", "pos": Vector3(-1800, 0, 1400), "msg": "Plaza smoke rises through a hole in the trees."},
		{"id": &"reels_pale", "name": "Pale Screen Seat", "pos": Vector3(40, 0, -3400), "msg": "The drive-in waits like a second moon."},
		{"id": &"stream_bench", "name": "Stream Listening Spot", "pos": Vector3(580, 0, -480), "msg": "Water talks louder than the road."},
	]


static func grassland_landmarks() -> Array[Dictionary]:
	## Extra natural landmarks — never registered on the mini-map.
	return [
		{"id": &"lm_arch_north", "name": "North Rock Arch", "pos": Vector3(-40, 0, -800), "kind": &"arch"},
		{"id": &"lm_falls_west", "name": "West Seep", "pos": Vector3(-480, 0, 160), "kind": &"waterfall"},
		{"id": &"lm_pond_south", "name": "South Mirror", "pos": Vector3(180, 0, 1900), "kind": &"pond"},
		{"id": &"lm_crystal_se", "name": "SE Crystal Fan", "pos": Vector3(2400, 0, 1800), "kind": &"crystal"},
		{"id": &"lm_cave_soft", "name": "Soft Mouth Cave", "pos": Vector3(1600, 0, -400), "kind": &"cave"},
		{"id": &"lm_tower_stub", "name": "Beacon Stub", "pos": Vector3(800, 0, -2400), "kind": &"tower"},
		{"id": &"lm_shrine_moss", "name": "Moss Shrine", "pos": Vector3(-800, 0, -100), "kind": &"shrine"},
		{"id": &"lm_log_bridge", "name": "Log Bridge", "pos": Vector3(360, 0, 700), "kind": &"bridge"},
	]
